### ISSUE TITLE
is it also working ok for t440p with i5 4200m CPU

### ISSUE THREAD

**Issue by sky-dream** [Lastcraft484/T440p-Hackintosh-#1]
is it also working ok for t440p with i5 4200m CPU?

**Comment by Lastcraft484** [comment]
It should work just fine. It will not work for the i3 t440p without modification though. I believe if you use the 2011 education imac you can use an i3.

**Comment by sky-dream** [comment]
but i just used it. the laptop stuck in the logo after the first reboot. I don't know why, and I already tried 3 different T440p efi clover in the github, all failed after the first reboot, stuck at the logo, so strange...
![image](https://user-images.githubusercontent.com/6967263/78916913-c07dc980-7ac0-11ea-85c6-5e019d045e6c.jpg)

**Comment by sky-dream** [comment]
just checked the log on my laptop. found below error,
AMF :Only 255/256 slide values are usable!
Valid slides: 1-255,
any suggestion to fix it? tks

**Comment by Lastcraft484** [comment]
I am not sure, check over at the hackintosh Discord or subreddit 😄
